# Generated by Django 5.2.2 on 2026-01-30 20:09

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Backend',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField()),
                ('time', models.IntegerField(default=110)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('class_type', models.CharField(choices=[('IP', 'In-Person'), ('ON', 'Online')], max_length=2)),
            ],
        ),
    ]
