# Generated by Django 5.2.2 on 2026-01-30 20:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('essentially_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Backend',
            new_name='ClassSession',
        ),
    ]
